"""Turn assets/logo.jpg into src/external/ui/logo_pixels.h: the menu's logo, embedded in the exe as raw RGBA pixels.

Why embed raw pixels: the exe then needs no image decoder (no stb_image or similar dependency) and no file next to it.
The overlay uploads these pixels as an ImGui texture (ui/imgui_layer.cpp).

Run from the repo root after changing the logo (needs Pillow: pip install pillow):
    python tools/make_logo_header.py
The generated header is committed, so a normal build doesn't need Python.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

SIZE = 128  # pixels, square; drawn at up to ~110 px in the menu
ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "logo.jpg"
TARGET = ROOT / "src" / "external" / "ui" / "logo_pixels.h"
PER_LINE = 8


def main() -> None:
    image = Image.open(SOURCE).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    data = image.tobytes()  # R, G, B, A per pixel, rows top to bottom
    # One uint32 per pixel, laid out so the bytes in memory are R, G, B, A again (x64 is little-endian).
    words = [f"0x{int.from_bytes(data[i:i + 4], 'little'):08X}u" for i in range(0, len(data), 4)]
    lines = [", ".join(words[i:i + PER_LINE]) + "," for i in range(0, len(words), PER_LINE)]
    body = "\n".join("    " + line for line in lines)
    TARGET.write_text(
        "#pragma once\n\n"
        "// GENERATED by tools/make_logo_header.py from assets/logo.jpg. Don't edit by hand: re-run the script.\n"
        f"// The menu logo, {SIZE}x{SIZE} pixels, RGBA (bytes R, G, B, A in memory), rows top to bottom. PURE data.\n\n"
        "#include <cstdint>\n\n"
        "namespace ui::logo\n{\n"
        f"inline constexpr int kWidth = {SIZE};\n"
        f"inline constexpr int kHeight = {SIZE};\n"
        f"inline constexpr std::uint32_t kPixels[{SIZE * SIZE}] = {{\n{body}\n}};\n"
        "} // namespace ui::logo\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {TARGET} ({SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
